package com.bitchat.android.onboarding

enum class OnboardingState {
    SPLASH,
    CHECKING,
    BLUETOOTH_CHECK,
    LOCATION_CHECK,
    BATTERY_OPTIMIZATION_CHECK,
    PERMISSION_EXPLANATION,
    BACKGROUND_LOCATION_EXPLANATION,
    PERMISSION_REQUESTING,
    INITIALIZING,
    COMPLETE,
    ERROR
}
